// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: image_service.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	SizeX int32  `protobuf:"varint,2,opt,name=size_x,json=sizeX,proto3" json:"size_x,omitempty"`
	SizeY int32  `protobuf:"varint,3,opt,name=size_y,json=sizeY,proto3" json:"size_y,omitempty"`
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResizeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ResizeRequest) GetSizeX() int32 {
	if x != nil {
		return x.SizeX
	}
	return 0
}

func (x *ResizeRequest) GetSizeY() int32 {
	if x != nil {
		return x.SizeY
	}
	return 0
}

type GetSingleImgResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetSingleImgResult) Reset() {
	*x = GetSingleImgResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleImgResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleImgResult) ProtoMessage() {}

func (x *GetSingleImgResult) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleImgResult.ProtoReflect.Descriptor instead.
func (*GetSingleImgResult) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSingleImgResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Imgrequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*ResizeRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *Imgrequests) Reset() {
	*x = Imgrequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Imgrequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Imgrequests) ProtoMessage() {}

func (x *Imgrequests) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Imgrequests.ProtoReflect.Descriptor instead.
func (*Imgrequests) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{2}
}

func (x *Imgrequests) GetRequests() []*ResizeRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type Imgresult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Imgresult) Reset() {
	*x = Imgresult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Imgresult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Imgresult) ProtoMessage() {}

func (x *Imgresult) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Imgresult.ProtoReflect.Descriptor instead.
func (*Imgresult) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{3}
}

func (x *Imgresult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Imgresult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_image_service_proto protoreflect.FileDescriptor

var file_image_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x4f, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x69, 0x7a, 0x65, 0x5f,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x58, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x73, 0x69, 0x7a, 0x65, 0x59, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x47, 0x0a, 0x0b, 0x49, 0x6d, 0x67, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x38,
	0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0x31, 0x0a, 0x09, 0x49, 0x6d, 0x67, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xab, 0x01, 0x0a, 0x0c,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6d, 0x67, 0x12, 0x1c, 0x2e, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x49, 0x6d, 0x67, 0x73, 0x12,
	0x1a, 0x2e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x49, 0x6d, 0x67, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x18, 0x2e, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6d, 0x67, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_image_service_proto_rawDescOnce sync.Once
	file_image_service_proto_rawDescData = file_image_service_proto_rawDesc
)

func file_image_service_proto_rawDescGZIP() []byte {
	file_image_service_proto_rawDescOnce.Do(func() {
		file_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_service_proto_rawDescData)
	})
	return file_image_service_proto_rawDescData
}

var file_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_image_service_proto_goTypes = []interface{}{
	(*ResizeRequest)(nil),      // 0: image_service.ResizeRequest
	(*GetSingleImgResult)(nil), // 1: image_service.GetSingleImgResult
	(*Imgrequests)(nil),        // 2: image_service.Imgrequests
	(*Imgresult)(nil),          // 3: image_service.Imgresult
}
var file_image_service_proto_depIdxs = []int32{
	0, // 0: image_service.Imgrequests.requests:type_name -> image_service.ResizeRequest
	0, // 1: image_service.ImageService.GetSingleImg:input_type -> image_service.ResizeRequest
	2, // 2: image_service.ImageService.getMultiImgs:input_type -> image_service.Imgrequests
	1, // 3: image_service.ImageService.GetSingleImg:output_type -> image_service.GetSingleImgResult
	3, // 4: image_service.ImageService.getMultiImgs:output_type -> image_service.Imgresult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_image_service_proto_init() }
func file_image_service_proto_init() {
	if File_image_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_image_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleImgResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Imgrequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Imgresult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_service_proto_goTypes,
		DependencyIndexes: file_image_service_proto_depIdxs,
		MessageInfos:      file_image_service_proto_msgTypes,
	}.Build()
	File_image_service_proto = out.File
	file_image_service_proto_rawDesc = nil
	file_image_service_proto_goTypes = nil
	file_image_service_proto_depIdxs = nil
}
